#pragma once

#define __NEW_EXCHANGE_WINDOW__
#define ENABLE_QUIVER_SYSTEM
#define ENABLE_HWID_BAN_SYSTEM
#define ENABLE_D_NJGUILD
#define ENABLE_FULL_NOTICE
#define ENABLE_MAINTENANCE_SYSTEM
#define ENABLE_EXTEND_COSTUME_TIME
#define ENABLE_WEAPON_COSTUME_SYSTEM
#define ENABLE_EXTEND_ITEMS_STACK
//#define __IMPROVED_HANDSHAKE_PROCESS__
#define __EXTENDED_COSTUME_RECHARGE__
#define ITEM_CHECKINOUT_UPDATE
#define ENABLE_LETTER_EVENT
#define ENABLE_EASTER_EVENT
//#define ENABLE_GOTO_LAG_FIX // disabled temporary
#define ENABLE_PET_COSTUME_SYSTEM
#define ENABLE_PERMANENT_AFFECT
#define RENEWAL_DEAD_PACKET
#define ENABLE_PARTY_GROUP_BUFF

#define ENABLE_EXTEND_ITEM_AWARD
#ifdef ENABLE_EXTEND_ITEM_AWARD
	#define USE_ITEM_AWARD_CHECK_ATTRIBUTES
#endif

#define ENABLE_SHOW_CHEST_DROP
#define ENABLE_RENEWAL_SHOPEX
#define __VIEW_TARGET_PLAYER_HP__
#define __VIEW_TARGET_DECIMAL_HP__
#define ENABLE_SORT_INVENTORY
#define ENABLE_NEWSTUFF
#define ENABLE_PLAYER_PER_ACCOUNT5
#define ENABLE_PORT_SECURITY
#define ENABLE_CUBE_RENEWAL
#define ENABLE_MOVE_CHANNEL
#define ENABLE_DICE_SYSTEM
#define ENABLE_ANTIEXP_RING
#define ENABLE_DROP_DIALOG
#define ENABLE_MESSENGER_TEAM
#define ENABLE_EXTEND_INVEN_SYSTEM
#define ENABLE_GLOBAL_CHAT
#define ENABLE_SPECIAL_INVENTORY
#define ENABLE_EXTENDED_ITEMNAME_ON_GROUND
#define ENABLE_MOUNT_COSTUME_SYSTEM
#define ENABLE_REMOVE_LIMIT_GOLD
#define ENABLE_SWITCHBOT
#define WJ_ENABLE_PICKUP_ITEM_EFFECT
#define ENABLE_BIOLOG_SYSTEM
#ifdef ENABLE_BIOLOG_SYSTEM
#define MISSION_MAX_BIOLOG 10
#endif

#define WJ_LEVEL_UPDATE_FIX
#define WJ_CHARACTER_UPDATE_FIX

#define ENABLE_ANTI_LOGIN_BRUTEFORCE
#define __NEW_OFFLINESHOP_SPAWN__
#define __ENABLE_NEW_OFFLINESHOP__
#ifdef __ENABLE_NEW_OFFLINESHOP__
#define __ENABLE_NEW_SHOP_IN_CITIES__
#define __ENABLE_LARGE_DYNAMIC_PACKET__
#endif

#ifdef _WIN32
#define ENABLE_OFFLINESHOP_DEBUG
#endif

#ifdef ENABLE_OFFLINESHOP_DEBUG
#ifdef _WIN32
#define OFFSHOP_DEBUG(fmt , ...) sys_log(0,"%s:%d >> " fmt , __FUNCTION__ , __LINE__, __VA_ARGS__)
#else
#define OFFSHOP_DEBUG(fmt , args...) sys_log(0,"%s:%d >> " fmt , __FUNCTION__ , __LINE__, ##args)
#endif
#else
#define OFFSHOP_DEBUG(...)
#endif

//#define ENABLE_NEW_OFFLINESHOP_LOGS
#define __ENABLE_LARGE_DYNAMIC_PACKET__
// #define ENABLE_PC_ITEM_DROP_PENALTY
#define ENABLE_HAIR_SPECULAR
#define ENABLE_NO_MOUNT_CHECK
#define ENABLE_NULLIFYAFFECT_LIMIT
#define ENABLE_YANG_BOMB_FIX
#define ENABLE_BATTLE_PASS

//#define ENABLE_HUNTING_SYSTEM
#ifdef ENABLE_HUNTING_SYSTEM
#define HUNTING_MISSION_COUNT 90
#define HUNTING_MONEY_TABLE_SIZE 9
#define HUNTING_EXP_TABLE_SIZE 9
#endif

#define ENABLE_MESSENGER_BLOCK
#define ENABLE_WORLD_BOSS
#define ENABLE_TARGET_INFO_DROP
#define __INGAME_WIKI__ // Wiki In Game
#define ENABLE_ADMIN_PAGE
#define ENABLE_RENEWAL_ITEMS_PACKETS
#define ENABLE_RANKING_SYSTEM
#define ENABLE_EVENT_MANAGER
#ifdef ENABLE_EVENT_MANAGER
#define ENABLE_EVENT_FIND_NPC
#endif

