#ifndef __INC_SERVICE_H__
#define __INC_SERVICE_H__

#define ENABLE_AUTODETECT_INTERNAL_IP
#define ENABLE_PROXY_IP
#define ENABLE_PORT_SECURITY
#define _IMPROVED_PACKET_ENCRYPTION_ // 패킷 암호화 개선
//#define __AUCTION__
#define __PET_SYSTEM__
#define __UDP_BLOCK__


#define ENABLE_EXTRA_LOGIN_SECURITY_KEY
#ifdef ENABLE_EXTRA_LOGIN_SECURITY_KEY
	#define EXTRA_LOGIN_SECURITY_KEY "460cZ71kqi6z"
#endif
#endif
